### ISSUE TITLE
Not forked

### ISSUE THREAD

**Issue by maximebories** [t-abraham/instagent#2]
Hello,

Why did you not properly forked from the original repository ? This goes against Community Guidelines and raises trust issues as one have to manually check code diff from the original repo.

Thanks.

**Comment by ghostkernel-core** [comment]
Hi,

To be honest I initially thought to keep this project as private but later when I found that the original owner for ostragram is inactive I Decided to make the private one as public and carry on the developments.

Also in the next version of the release I am replacing the whole API since the currently used one is unmaintained and also doesn't not solve challenges or other issues
